package task.trak.app.client.gui.viewmodel.event;

public enum CommandEventType {
    TASK_CREATED, TASK_UPDATED, TASK_DELETED, TASK_RETRIEVED, TASK_LIST,
    PROJECT_CREATED, PROJECT_UPDATED, PROJECT_DELETED, PROJECT_RETRIEVED, PROJECT_LIST,
    SPRINT_CREATED, SPRINT_UPDATED, SPRINT_DELETED, SPRINT_RETRIEVED, SPRINT_LIST,
    BACKLOG_CREATED, BACKLOG_UPDATED, BACKLOG_DELETED, BACKLOG_RETRIEVED,
    USER_CREATED, USER_UPDATED, USER_DELETED, USER_RETRIEVED,
    LOGIN, LOGOUT,
    INFO, DETAIL, CURRENT_TASK, START_TASK, END_TASK, COMPLETE_TASK,
    SPRINT_PLAN, ADD_MEMBER, ADD_TASK,
    ERROR, UNKNOWN
}
